AWSTemplateFormatVersion: '2010-09-09'
Description: AuthBridge DynamoDB Single-Table Design

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: Deployment stage

Resources:
  AuthBridgeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuthBridgeTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        # Primary Key
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        # GSI1: Query by client + status (verifications, sessions)
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        # GSI2: Query by date (verifications, API keys)
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        # GSI3: Query audit logs by user
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
        # GSI4: API Key lookup by hashed key
        - AttributeName: GSI4PK
          AttributeType: S
        - AttributeName: GSI4SK
          AttributeType: S
        # GSI5: Audit logs by user
        - AttributeName: GSI5PK
          AttributeType: S
        - AttributeName: GSI5SK
          AttributeType: S
        # GSI6: Audit logs by resource
        - AttributeName: GSI6PK
          AttributeType: S
        - AttributeName: GSI6SK
          AttributeType: S
        # GSI7: Audit logs by action type
        - AttributeName: GSI7PK
          AttributeType: S
        - AttributeName: GSI7SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI4: API Key lookup by hashed key (O(1) lookup instead of Scan)
        # PK: APIKEY_HASH#{hashedKey} - enables direct lookup by API key
        - IndexName: GSI4-ApiKeyLookup
          KeySchema:
            - AttributeName: GSI4PK
              KeyType: HASH
            - AttributeName: GSI4SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI5: Audit logs by user (query all actions by specific user)
        # PK: USER#{userId} - enables user-specific audit queries
        - IndexName: GSI5-AuditByUser
          KeySchema:
            - AttributeName: GSI5PK
              KeyType: HASH
            - AttributeName: GSI5SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI6: Audit logs by resource (query all actions on specific resource)
        # PK: {resourceType}#{resourceId} - enables resource-specific audit queries
        - IndexName: GSI6-AuditByResource
          KeySchema:
            - AttributeName: GSI6PK
              KeyType: HASH
            - AttributeName: GSI6SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI7: Audit logs by action type (query all instances of specific action)
        # PK: ACTION#{action} - enables action-type audit queries
        - IndexName: GSI7-AuditByAction
          KeySchema:
            - AttributeName: GSI7PK
              KeyType: HASH
            - AttributeName: GSI7SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Project
          Value: AuthBridge
        - Key: Stage
          Value: !Ref Stage

Outputs:
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref AuthBridgeTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
  TableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt AuthBridgeTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
