name: Test
description: Test the project

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm i --no-frozen-lockfile

    - name: Test
      shell: bash
      run: pnpm test

    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install --with-deps chromium
      working-directory: sdks/web-sdk

    - name: Test e2e
      shell: bash
      run: pnpm test:e2e --project=chromium
      working-directory: sdks/web-sdk
      env:
        CI: true

    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: sdks/web-sdk/playwright-report/
        retention-days: 7
